micronaut:
  application:
    name: todo
  security:
    endpoints:
      login:
        path: /auth/signin
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:SUPER_SECURE_SECREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEET}"'


datasources:
  default:
    url: "jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1"
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: com.ferroeduardo.entity
    properties:
      hibernate:
        hbm2ddl:
          auto: update